-- Create a table for users (profiles)
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  level text default 'Débutant',
  points integer default 0,
  followers_count integer default 0,
  following_count integer default 0,
  updated_at timestamp with time zone
);

-- Set up Row Level Security (RLS) for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for coffee tastings (posts)
create table tastings (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  coffee_name text not null,
  brand text,
  roast text,
  rating integer not null check (rating >= 1 and rating <= 5),
  tags text[] default '{}',
  review text,
  likes_count integer default 0,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for tastings
alter table tastings enable row level security;

create policy "Tastings are viewable by everyone."
  on tastings for select
  using ( true );

create policy "Users can insert their own tastings."
  on tastings for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own tastings."
  on tastings for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own tastings."
  on tastings for delete
  using ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', '☕️');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function after a user signs up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
