const { createClient } = require('@supabase/supabase-js'); const path = require('path'); require('dotenv').config({ path: path.resolve(__dirname, '../.env.local') }); const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY); const coffeeData = [
  { name: 'Qualità Oro - Grains', brand: 'Lavazza', image_url: 'https://m.media-amazon.com/images/I/81N2A6GvS4L._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B000SDKM0U', category: 'Grains' },
  { name: 'Qualità Rossa - Moulu', brand: 'Lavazza', image_url: 'https://m.media-amazon.com/images/I/71R1yH8N8ZL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B003WTRP6A', category: 'Moulu' },
  { name: 'L\'OR Espresso Absolu - Capsules x100', brand: 'L\'OR', image_url: 'https://m.media-amazon.com/images/I/71uV4p7-99L._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B07SNT8VCH', category: 'Capsules' },
  { name: 'L\'OR Espresso Forza - Capsules', brand: 'L\'OR', image_url: 'https://m.media-amazon.com/images/I/81xG-Y3V4cL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B01MT2G8S3', category: 'Capsules' },
  { name: 'Carte Noire Classique - Moulu', brand: 'Carte Noire', image_url: 'https://m.media-amazon.com/images/I/81S8fWp7N5L._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B0050IGL7O', category: 'Moulu' },
  { name: 'Pellini Top - 100% Arabica Grains', brand: 'Pellini', image_url: 'https://m.media-amazon.com/images/I/71f-T3P6M+L._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B001E5E2P6', category: 'Grains' },
  { name: 'Starbucks Pike Place Roast - Grains', brand: 'Starbucks', image_url: 'https://m.media-amazon.com/images/I/81vYV0i9T5L._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B07N9D9X6K', category: 'Grains' },
  { name: 'Illy Classico - Grains 250g', brand: 'Illy', image_url: 'https://m.media-amazon.com/images/I/71-0+D4e8oL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B000S97J8M', category: 'Grains' },
  { name: 'Melitta BellaCrema LaCrema - Grains', brand: 'Melitta', image_url: 'https://m.media-amazon.com/images/I/81N9W7S7iNL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B000RZF9T0', category: 'Grains' },
  { name: 'San Marco - Moulu N°7', brand: 'San Marco', image_url: 'https://m.media-amazon.com/images/I/81S9W7S7iNL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B0050IGM9K', category: 'Moulu' },
  { name: 'Malongo Blue Mountain - Grains', brand: 'Malongo', image_url: 'https://m.media-amazon.com/images/I/71S9W7S7iNL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B00B1R7M5S', category: 'Grains' },
  { name: 'Cafe Royal Espresso - Capsules x100', brand: 'Cafe Royal', image_url: 'https://m.media-amazon.com/images/I/81S9W7S7iNL._AC_SL1500_.jpg', url: 'https://www.amazon.fr/dp/B00F9V7M5S', category: 'Capsules' }
]; async function seed() { const { data, error } = await supabase.from('coffees').upsert(coffeeData, { onConflict: 'url' }); if (error) console.error('Error:', error.message); else console.log('Successfully added Amazon Best Sellers to the catalog.'); } seed();
